"""init

Revision ID: 0682fbf6dceb
Revises: 
Create Date: 2017-06-12 22:48:13.993000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0682fbf6dceb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Exclusiveplanning',
    sa.Column('Eid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Einfo', sa.String(length=64), nullable=True),
    sa.Column('Elink', sa.String(length=100), nullable=True),
    sa.Column('Eimg', sa.String(length=100), nullable=True),
    sa.Column('Etitle', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Hotlist',
    sa.Column('Hid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Hinfo', sa.String(length=64), nullable=True),
    sa.Column('Hlink', sa.String(length=100), nullable=True),
    sa.Column('Himg', sa.String(length=100), nullable=True),
    sa.Column('Htitle', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peakviewingtime',
    sa.Column('Pid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Pinfo', sa.String(length=64), nullable=True),
    sa.Column('Plink', sa.String(length=100), nullable=True),
    sa.Column('Pimg', sa.String(length=100), nullable=True),
    sa.Column('Ptitle', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('super_drama',
    sa.Column('Sid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Sinfo', sa.String(length=64), nullable=True),
    sa.Column('Slink', sa.String(length=100), nullable=True),
    sa.Column('Simg', sa.String(length=100), nullable=True),
    sa.Column('Stitle', sa.String(length=50), nullable=True),
    sa.Column('Stime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('super_drama')
    op.drop_table('peakviewingtime')
    op.drop_table('Hotlist')
    op.drop_table('Exclusiveplanning')
    # ### end Alembic commands ###
